# Generated by Django 5.0 on 2024-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.CharField(max_length=128),
        ),
    ]
